main()
{
    if(2<3)
    {
        if(3<7)
        {
            if(7<9)
                printf("banglore");
            else
                printf("computer");
        }
        printf("education");
    }
    else
        printf("bathinda");
        printf("india");
}
