package com.forensic.mart.SmallFeatures;

public class Country_id_lib {
    public int gen(String gen) {
        switch (gen) {
            case "AX":
                return 1;
            case "AL":
                return 2;
            case "DZ":
                return 3;
            case "AS":
                return 4;
            case "AD":
                return 5;
            case "AO":
                return 6;
            case "AI":
                return 7;
            case "AQ":
                return 8;
            case "AG":
                return 9;
            case "AR":
                return 10;
            case "AM":
                return 11;
            case "AW":
                return 12;
            case "AU":
                return 13;
            case "AT":
                return 14;
            case "AZ":
                return 15;
            case "BS":
                return 16;
            case "BH":
                return 17;
            case "BD":
                return 18;
            case "BB":
                return 19;
            case "BY":
                return 20;
            case "BE":
                return 21;
            case "BZ":
                return 22;
            case "BJ":
                return 23;
            case "BM":
                return 24;
            case "BT":
                return 25;
            case "BO":
                return 26;
            case "BA":
                return 27;
            case "BW":
                return 28;
            case "BV":
                return 29;
            case "BR":
                return 30;
            case "IO":
                return 31;
            case "BN":
                return 32;
            case "BG":
                return 33;
            case "BF":
                return 34;
            case "BI":
                return 35;
            case "KH":
                return 36;
            case "CM":
                return 37;
            case "CA":
                return 38;
            case "CV":
                return 39;
            case "KY":
                return 40;
            case "CF":
                return 41;
            case "TD":
                return 42;
            case "CL":
                return 43;
            case "CN":
                return 44;
            case "CX":
                return 45;
            case "CC":
                return 46;
            case "CO":
                return 47;
            case "KM":
                return 48;
            case "CG":
                return 49;
            case "CK":
                return 50;
            case "CR":
                return 51;
            case "HR":
                return 52;
            case "CU":
                return 53;
            case "CY":
                return 54;
            case "CZ":
                return 55;
            case "DK":
                return 56;
            case "DJ":
                return 57;
            case "DM":
                return 58;
            case "DO":
                return 59;
            case "TP":
                return 60;
            case "EC":
                return 61;
            case "EG":
                return 62;
            case "SV":
                return 63;
            case "GQ":
                return 64;
            case "ER":
                return 65;
            case "EE":
                return 66;
            case "ET":
                return 67;
            case "FK":
                return 68;
            case "FO":
                return 69;
            case "FJ":
                return 70;
            case "FI":
                return 71;
            case "FR":
                return 72;
            case "FX":
                return 73;
            case "GF":
                return 74;
            case "PF":
                return 75;
            case "TF":
                return 76;
            case "GA":
                return 77;
            case "GM":
                return 78;
            case "GE":
                return 79;
            case "DE":
                return 80;
            case "GH":
                return 81;
            case "GI":
                return 82;
            case "GK":
                return 83;
            case "GR":
                return 84;
            case "GL":
                return 85;
            case "GD":
                return 86;
            case "GP":
                return 87;
            case "GU":
                return 88;
            case "GT":
                return 89;
            case "GN":
                return 90;
            case "GW":
                return 91;
            case "GY":
                return 92;
            case "HT":
                return 93;
            case "HM":
                return 94;
            case "HN":
                return 95;
            case "HK":
                return 96;
            case "HU":
                return 97;
            case "IS":
                return 98;
            case "IN":
                return 99;
            case "IM":
                return 100;
            case "ID":
                return 101;
            case "IR":
                return 102;
            case "IQ":
                return 103;
            case "IE":
                return 104;
            case "IL":
                return 105;
            case "IT":
                return 106;
            case "CI":
                return 107;
            case "JE":
                return 108;
            case "JM":
                return 109;
            case "JP":
                return 110;
            case "JO":
                return 111;
            case "KZ":
                return 112;
            case "KE":
                return 113;
            case "KI":
                return 114;
            case "KP":
                return 115;
            case "KR":
                return 116;
            case "XK":
                return 117;
            case "KW":
                return 118;
            case "KG":
                return 119;
            case "LA":
                return 120;
            case "LV":
                return 121;
            case "LB":
                return 122;
            case "LS":
                return 123;
            case "LR":
                return 124;
            case "LY":
                return 125;
            case "LI":
                return 126;
            case "LT":
                return 127;
            case "LU":
                return 128;
            case "MO":
                return 129;
            case "MK":
                return 130;
            case "MG":
                return 131;
            case "MW":
                return 132;
            case "MY":
                return 133;
            case "MV":
                return 134;
            case "ML":
                return 135;
            case "MT":
                return 136;
            case "MH":
                return 137;
            case "MQ":
                return 138;
            case "MR":
                return 139;
            case "MU":
                return 140;
            case "TY":
                return 141;
            case "MX":
                return 142;
            case "FM":
                return 143;
            case "MD":
                return 144;
            case "MC":
                return 145;
            case "MN":
                return 146;
            case "ME":
                return 147;
            case "MS":
                return 148;
            case "MA":
                return 149;
            case "MZ":
                return 150;
            case "MM":
                return 151;
            case "NA":
                return 152;
            case "NR":
                return 153;
            case "NP":
                return 154;
            case "NL":
                return 155;
            case "AN":
                return 156;
            case "NC":
                return 157;
            case "NZ":
                return 158;
            case "NI":
                return 159;
            case "NE":
                return 160;
            case "NG":
                return 161;
            case "NU":
                return 162;
            case "NF":
                return 163;
            case "MP":
                return 164;
            case "NO":
                return 165;
            case "OM":
                return 166;
            case "PK":
                return 167;
            case "PW":
                return 168;
            case "PS":
                return 169;
            case "PA":
                return 170;
            case "PG":
                return 171;
            case "PY":
                return 172;
            case "PE":
                return 173;
            case "PH":
                return 174;
            case "PN":
                return 175;
            case "PL":
                return 176;
            case "PT":
                return 177;
            case "PR":
                return 178;
            case "QA":
                return 179;
            case "RE":
                return 180;
            case "RO":
                return 181;
            case "RU":
                return 182;
            case "RW":
                return 183;
            case "KN":
                return 184;
            case "LC":
                return 185;
            case "VC":
                return 186;
            case "WS":
                return 187;
            case "SM":
                return 188;
            case "ST":
                return 189;
            case "SA":
                return 190;
            case "SN":
                return 191;
            case "RS":
                return 192;
            case "SC":
                return 193;
            case "SL":
                return 194;
            case "SG":
                return 195;
            case "SK":
                return 196;
            case "SI":
                return 197;
            case "SB":
                return 198;
            case "SO":
                return 199;
            case "ZA":
                return 200;
            case "GS":
                return 201;
            case "SS":
                return 202;
            case "ES":
                return 203;
            case "LK":
                return 204;
            case "SH":
                return 205;
            case "PM":
                return 206;
            case "SD":
                return 207;
            case "SR":
                return 208;
            case "SJ":
                return 209;
            case "SZ":
                return 210;
            case "SE":
                return 211;
            case "CH":
                return 212;
            case "SY":
                return 213;
            case "TW":
                return 214;
            case "TJ":
                return 215;
            case "TZ":
                return 216;
            case "TH":
                return 217;
            case "TG":
                return 218;
            case "TK":
                return 219;
            case "TO":
                return 220;
            case "TT":
                return 221;
            case "TN":
                return 222;
            case "TR":
                return 223;
            case "TM":
                return 224;
            case "TC":
                return 225;
            case "TV":
                return 226;
            case "UG":
                return 227;
            case "UA":
                return 228;
            case "AE":
                return 229;
            case "GB":
                return 230;
            case "US":
                return 231;
            case "UM":
                return 232;
            case "UY":
                return 233;
            case "UZ":
                return 234;
            case "VU":
                return 235;
            case "VA":
                return 236;
            case "VE":
                return 237;
            case "VN":
                return 238;
            case "VG":
                return 239;
            case "VI":
                return 240;
            case "WF":
                return 241;
            case "EH":
                return 242;
            case "YE":
                return 243;
            case "ZR":
                return 244;
            case "ZM":
                return 245;
            case "ZW":
                return 246;
            default:
                return 0;
        }


    }
}
